# Assignment Questions 

1.Using Numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [1]:
import numpy as np
np.random.rand(25)

array([0.48009568, 0.09071336, 0.59639269, 0.85485244, 0.75975094,
       0.96113506, 0.38915973, 0.66607438, 0.742312  , 0.38115338,
       0.03316925, 0.91328277, 0.05806791, 0.78752284, 0.63561085,
       0.91072262, 0.87161987, 0.60366336, 0.47763128, 0.97284664,
       0.74903249, 0.589211  , 0.37971979, 0.55187335, 0.42844905])

2.Create an array of 20 linear spaced points between 0 and 1

In [2]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

3.Declare a numpy array of values from 1 to 100 and make it into 10*10 matrix

In [3]:
import numpy as np
array = np.arange(100).reshape(10,10)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

4.Using the previously defind matrix print rows 1,5,6

In [4]:
print(array[[1,5,6]])

[[10 11 12 13 14 15 16 17 18 19]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


5.Using the previously defined matrix print elements from 3rd row to 10th row

In [5]:
print(array[3:])

[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


6.Using the previously defined matrix print all the elements from 4th row to 8th row

In [6]:
print(array[0:10,3:8])

[[ 3  4  5  6  7]
 [13 14 15 16 17]
 [23 24 25 26 27]
 [33 34 35 36 37]
 [43 44 45 46 47]
 [53 54 55 56 57]
 [63 64 65 66 67]
 [73 74 75 76 77]
 [83 84 85 86 87]
 [93 94 95 96 97]]


7.Using the same matrix print values from 3rd row 2nd column to 5th row 8th column

In [7]:
print(array[2:5,1:8])

[[21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]
 [41 42 43 44 45 46 47]]


8.Write a code to generate random 1000 numbers each in range (0,1) such that the count of all random points like are almost same

In [8]:
np.random.rand(100)

array([0.16308613, 0.46915478, 0.20934298, 0.03689919, 0.33513932,
       0.18405034, 0.61387551, 0.37014842, 0.29477537, 0.22097851,
       0.27014559, 0.41563872, 0.5849464 , 0.1235286 , 0.5831543 ,
       0.44498629, 0.15362408, 0.24783811, 0.52872971, 0.58323954,
       0.20320496, 0.30378049, 0.2599774 , 0.5521498 , 0.44128525,
       0.34382671, 0.36210695, 0.1301824 , 0.43523731, 0.54423469,
       0.13807111, 0.0185709 , 0.4586538 , 0.04199147, 0.09705259,
       0.96798923, 0.01305587, 0.05501424, 0.01158236, 0.24872581,
       0.56265666, 0.62276203, 0.76287825, 0.70277222, 0.00179721,
       0.08853167, 0.97591455, 0.85568029, 0.98422006, 0.46697233,
       0.16840112, 0.48814611, 0.1060646 , 0.45077662, 0.91910776,
       0.41011761, 0.85023501, 0.20982841, 0.27919018, 0.98380119,
       0.82455181, 0.81113403, 0.20949281, 0.25920579, 0.79146494,
       0.56274453, 0.78204698, 0.90273547, 0.74982931, 0.08919481,
       0.31528872, 0.37426338, 0.04701456, 0.22717154, 0.38725

9.Write the commands to get standard deviation, mean,median,mode for a given vector

In [9]:
a = np.array([[7, 2], [5, 4]])
np.mean(a)

4.5

In [10]:
np.median(a)

4.5

In [11]:
np.std(a)

1.8027756377319946

In [12]:
a = np.array([[7, 1, 1, 7],
             [9, 4, 3, 8],
             [6, 1, 9, 7],
             [9, 7, 2, 5],
             [5, 1, 5, 9]])
a

array([[7, 1, 1, 7],
       [9, 4, 3, 8],
       [6, 1, 9, 7],
       [9, 7, 2, 5],
       [5, 1, 5, 9]])

In [13]:
from scipy import stats
stats.mode(a)

ModeResult(mode=array([[9, 1, 1, 7]]), count=array([[2, 3, 1, 2]]))